spring:
  redis:
    host: 175.178.184.40
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 8
        max-wait: 8
      shutdown-timeout: 20000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.184.40:3344/godwealth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    #url: jdbc:mysql://localhost:3306/godwealth?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    #1990@linhongfei
    druid:
      initial-size: 1 #初始化连接数
      min-idle: 1 #最小空闲连接
      max-active: 20 #最大活动连接
      test-on-borrow: true
      stat-view-servlet:
        allow: true
    hikari:
      connection-timeout: 10000
#  rabbitmq:
#    host: 175.178.184.40
#    port: 5672
#    password: guest
#    username: guest
#    listener:
#      simple:
#        acknowledge-mode: auto
#        prefetch: 1
#        default-requeue-rejected: false
server:
  port: 8081
  servlet:
    context-path: /godwealth/api
# SpringBoot整合Mybatis配置
mybatis:
  # 定义别名映射包：实现对象映射
  type-aliases-package: com.godwealth.entity
  # 加载映射文件，一个接口对应一个映射文件
  mapper-locations: classpath:/mappers/*.xml
  # 开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
##mybatis配置
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true #开启驼峰映射
#  # model的包
#  type-aliases-package: com.godwealth.entity
#  mapper-locations: classpath:mappers/*Mapper.xml
logging:
  config: classpath:logback-spring.xml
